<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gdb-mi</string>
		<string>gdb</string>
	</array>
	<key>name</key>
	<string>GDB MI</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#gdb-prompt</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#out-of-band-record</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#result-record</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#command</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>cli-command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\d*)[^\^\~\@&amp;=+*-].*$</string>
			<key>name</key>
			<string>meta.command.cli.gdb-mi</string>
		</dict>
		<key>comma</key>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.comma.gdb-mi</string>
		</dict>
		<key>command</key>
		<dict>
			<key>name</key>
			<string>meta.command.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mi-command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cli-command</string>
				</dict>
			</array>
		</dict>
		<key>console-stream-output</key>
		<dict>
			<key>begin</key>
			<string>^(\~)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-console-stream-output.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.stream-output.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cstring</string>
				</dict>
			</array>
		</dict>
		<key>cstring</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.gdb-mi</string>
				</dict>
			</array>
		</dict>
		<key>exec-async-record</key>
		<dict>
			<key>begin</key>
			<string>^(\d*)(\*)([a-zA-Z][a-zA-Z0-9_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-record.gdb-mi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.async-class.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.async-record.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>gdb-prompt</key>
		<dict>
			<key>match</key>
			<string>^(\(gdb\))\s*$</string>
			<key>name</key>
			<string>entity.name.tag.prompt.gdb-mi</string>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-list.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.end-list.gdb-mi</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.list.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>log-stream-output</key>
		<dict>
			<key>begin</key>
			<string>^(&amp;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-log-stream-output.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.stream-output.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cstring</string>
				</dict>
			</array>
		</dict>
		<key>mi-command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\d*)-.*$</string>
			<key>name</key>
			<string>meta.command.mi.gdb-mi</string>
		</dict>
		<key>notify-async-record</key>
		<dict>
			<key>begin</key>
			<string>^(\d*)(=)([a-zA-Z][a-zA-Z0-9_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-record.gdb-mi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.async-class.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.async-record.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>out-of-band-record</key>
		<dict>
			<key>name</key>
			<string>meta.out-of-band-record.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#console-stream-output</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#target-stream-output</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#log-stream-output</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#notify-async-record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#status-async-record</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exec-async-record</string>
				</dict>
			</array>
		</dict>
		<key>result</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_-][a-zA-Z0-9_-]*)\s*(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.gdb-mi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[,\]\}]|^\(gdb\)\s*$|$)</string>
			<key>name</key>
			<string>meta.result.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>result-record</key>
		<dict>
			<key>begin</key>
			<string>^(\d*)(\^)(done|running|connected|error|exit)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-record.gdb-mi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.result-record-type.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^\(gdb\)\s*$|$)</string>
			<key>name</key>
			<string>meta.result-record.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>status-async-record</key>
		<dict>
			<key>begin</key>
			<string>^(\d*)(\+)([a-zA-Z][a-zA-Z0-9_-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.token.gdb-mi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-record.gdb-mi</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.async-class.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.async-record.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>target-stream-output</key>
		<dict>
			<key>begin</key>
			<string>^(\@)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-target-stream-output.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.stream-output.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cstring</string>
				</dict>
			</array>
		</dict>
		<key>tuple</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.begin-tuple.gdb-mi</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.end-tuple.gdb-mi</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tuple.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#result</string>
				</dict>
			</array>
		</dict>
		<key>value</key>
		<dict>
			<key>name</key>
			<string>meta.value.gdb-mi</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tuple</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gdb-mi</string>
	<key>uuid</key>
	<string>32d70691-1958-4f86-81ed-2d331211f4a0</string>
</dict>
</plist>
